baseurl = "https://horeaporutiu.github.io/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Horea's Blog"
disqusShortname = "https-horeaporutiu-github-io-1"
googleAnalytics = "UA-98632670-1"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"

	analytics = "code-here"

	email = "horeaporutiu@gmail.com"

	profilepic = "img/profPic.JPG"

	title = "Horea Porutiu"
	subtitle = "Software Engineer"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/horeaporutiu"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/horeaporutiu"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com/in/hporutiu"
	[[params.socialbuttons]]
	faicon = "stack-overflow"
	url = "https://stackoverflow.com/users/6785292/horea-porutiu?tab=profile"

	[[params.navlinks]]
	name = "About"
	url = "about/"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"

	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorials/"
