baseurl             = "https://horeaporutiu.github.io/"
languageCode        = "en-us"
title               = "Horea Porutiu"
theme               = "introduction"
#enforce_ssl         = "your-url.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
disqusshortname   = "https-horeaporutiu-github-io-1" # Enable Disqus for comments
googleAnalytics   = "UA-98632670-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Horea Porutiu" # Full name shows on blog post pages
firstname     = "Horea" # First name shows in introduction on main page
tagline       = "I write and talk code." # Appears after the introduction
introheight   = "large" # Input either 'medium' or 'large' or 'fullheight'
theme         = "light" # Choose 'light' or 'dark'
avatar        = "img/profPic.JPG" # Path to image in static folder eg. img/avatar.png
email         = "horeaporutiu@gmail.com" # Shows in contact section, or leave blank to omit
localtime     = true # Show your current local time in contact section
timezone      = "America/Los_Angeles" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "A blog to discuss emerging tech."
faviconfile   = "img/favicon.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "Horea Porutiu © 2017. All rights reserved." # Text to show in footer (overrides default text)

fadein          = true # Turn on/off the fade-in effect

showblog        = true # Show Blog section on home page
showallposts    = true # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "https://stockbot.mybluemix.net/"
project1img     = "img/stockBot.png"
project1title   = "StockBot: A chatbot for getting stock quotes in real time."


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

# 	# Social buttons for sidebar
# 	# Each of these are optional
# 	[[params.socialbuttons]]
# 	faicon = "github"
# 	url = "https://github.com/horeaporutiu"
# 	[[params.socialbuttons]]
# 	faicon = "twitter"
# 	url = "https://twitter.com/horeaporutiu"
# 	[[params.socialbuttons]]
# 	faicon = "linkedin"
# 	url = "https://linkedin.com/in/hporutiu"
# 	[[params.socialbuttons]]
# 	faicon = "stack-overflow"
# 	url = "https://stackoverflow.com/users/6785292/horea-porutiu?tab=profile"
# 	[[params.socialbuttons]]
# 	faicon = "youtube"
# 	url = "https://www.youtube.com/user/horeaporutiu"
#

[[params.social]]
url = "https://twitter.com/horeaporutiu/"
icon = "twitter"

[[params.social]]
url = "https://github.com/horeaporutiu"
icon = "github"

[[params.social]]
url = "https://linkedin.com/in/hporutiu"
icon = "linkedin"

[[params.social]]
url = "https://www.youtube.com/user/horeaporutiu"
icon = "youtube"

[[params.social]]
url = "https://stackoverflow.com/users/6785292/horea-porutiu?tab=profile"
icon = "stack-overflow"

# baseurl = "https://horeaporutiu.github.io/"
# theme = "hugo-geo"
# relativeURLs = false
# languageCode = "en-us"
# title = "Horea's Blog"
# disqusShortname = "https-horeaporutiu-github-io-1"
# googleAnalytics = "UA-98632670-1"
# paginate = 5
#
# [taxonomies]
# 	tag = "tags"
# 	tutorial = "tutorials"
#
# [params]
# 	showglobe = true
#
# 	favicon = "favicon.ico"
#
# 	analytics = "code-here"
#
# 	email = "horeaporutiu@gmail.com"
#
# 	profilepic = "img/profPic.JPG"
#
# 	title = "Horea Porutiu"
# 	subtitle = "Software Engineer"
#
# 	# Social buttons for sidebar
# 	# Each of these are optional
# 	[[params.socialbuttons]]
# 	faicon = "github"
# 	url = "https://github.com/horeaporutiu"
# 	[[params.socialbuttons]]
# 	faicon = "twitter"
# 	url = "https://twitter.com/horeaporutiu"
# 	[[params.socialbuttons]]
# 	faicon = "linkedin"
# 	url = "https://linkedin.com/in/hporutiu"
# 	[[params.socialbuttons]]
# 	faicon = "stack-overflow"
# 	url = "https://stackoverflow.com/users/6785292/horea-porutiu?tab=profile"
# 	[[params.socialbuttons]]
# 	faicon = "youtube"
# 	url = "https://www.youtube.com/user/horeaporutiu"
#
# 	[[params.navlinks]]
# 	name = "Home"
# 	url = ""
#
# 	[[params.navlinks]]
# 	name = "About"
# 	url = "about/"
#
# 	[[params.navlinks]]
# 	name = "Blog"
# 	url = "post/"
#
# 	[[params.navlinks]]
# 	name = "Tutorials"
# 	url = "tutorials/"
